### PR TITLE
Pin cyberchef shortcut instead of chrome

### PR DESCRIPTION
**Pull request by emtuls**
This attempts to fix https://github.com/mandiant/flare-vm/issues/559

To complete it, we will also need to merge: https://github.com/mandiant/VM-Packages/pull/844

Closes https://github.com/mandiant/flare-vm/issues/559

### CODE REVIEW

**Review by Ana06 — APPROVED** [review]
Thanks @emtuls!

**Comment by emtuls** [comment]
The CLA has been running for almost 24 hours...Not sure what we should do. Seems bugged. 😕

**Comment by Ana06** [comment]
I don't know how we can re-run it. We could re-push to force it to re-run. But I think we can just merge the PR without the CLA check, we know it is fine as there are only commits from you.

**Comment by emtuls** [comment]
I attempted to rerun it once after it did that for ~2 hours and it still ended up doing the same thing...Thanks for merging!

**Pull request merged**
